[phases.setup]
aptPkgs = ["libatk1.0-0", "libatk-bridge2.0-0", "libgdk-pixbuf2.0-0", "libgtk-3-0", "libgbm-dev", "libnss3-dev", "libxss-dev", "libasound2t64", "xvfb", "fonts-liberation", "build-essential", "python3"]

[phases.install]
cmds = ["npm install", "npm rebuild sqlite3 --build-from-source"]
